version: '3'
networks: 
  web:
    external: true
  db:
services:
  zac-service:
    restart: always
    build: ./zac-service
    image: zac-service
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web
      - db
    depends_on:
      - mongodb-zac
    container_name: zac-services
  mongodb-zac:
    image: mongo:latest
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb/cdals:/data/db
      - /etc/localtime:/etc/localtime:ro
    networks:
      - db